# --------------- Spring Config ---------------
spring:
  application:
    name: cwq-ai-coding-station-backend
  profiles:
    active: local
  session:
    store-type: redis             # Session expired after 1 month
    timeout: 2600000
  datasource:
    url: jdbc:mysql://localhost:3306/ai_coding_station_memo?useSSL=false&serverTimezone=Asia/Shanghai
    username: ai_user
    password: ai_secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost             # Container name
      port: 6380                  # Your port in container name
      username: default
      password: redis_secret
      ttl: 3600                   # Self-defined persist time for RedisChatMemoryStoreConfig
  cache:
    type: caffeine
# --------------- Server Config ---------------
server:
  port: 8142
  servlet:
    context-path: /api
    session:
      timeout: 2600000            # 1 month
      cookie:                     # Expired after 1 month
        max-age: 2600000

# ------------- Springdoc-Openapi -------------
springdoc:
  group-configs:
    - group: 'user'
      packages-to-scan: com.cwq.project_aicodingstation.user.controller
    - group: 'app'
      packages-to-scan: com.cwq.project_aicodingstation.app.controller
    - group: 'chat'
      packages-to-scan: com.cwq.project_aicodingstation.chat.controller

# --------------- API doc tools ---------------
knife4j:
  enable: true
  setting:
    language: en

# -------------- AI Service API ---------------
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      # api-key: <Your API Key>
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
      response-format: json_object
      strict-json-schema: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      # api-key: <Your API Key>
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true

# ------------- AI Module Config --------------
ai:
  code:
    output-dir: ${user.dir}/tmp/code_output

# ------------- App Module Config -------------
app:
  deploy:
    output-dir: ${user.dir}/tmp/code_output
    deploy-dir: ${user.dir}/tmp/code_deploy
    deploy-host: http://localhost:8088
  screenshot:
    script-path: ${user.dir}/scripts/screenshot.js
    output-dir: ${user.dir}/tmp/covers
    base-url: http://localhost:8088/covers